# Generated by Django 5.1 on 2024-11-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='mileage_preventive_notification',
            field=models.FloatField(default=5000),
        ),
    ]
