# Generated by Django 5.1 on 2025-02-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='ppu',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
