# Generated by Django 5.1 on 2024-08-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_model_car_ppu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='extinguisher',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
