# Generated by Django 5.1 on 2024-08-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_car_extinguisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage_limit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='carkilometerlog',
            name='mileage',
            field=models.FloatField(),
        ),
    ]
