# Generated by Django 5.1 on 2024-10-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_car_mileage_alter_car_mileage_limit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carkilometerlog',
            old_name='mileage',
            new_name='next_mileage',
        ),
        migrations.AddField(
            model_name='carkilometerlog',
            name='prev_mileage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
