# Generated by Django 5.1 on 2024-10-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_mileage_carkilometerlog_next_mileage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='mileage_limit',
            new_name='mileage_preventive',
        ),
    ]
